### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError

### ISSUE THREAD

**Issue by aminaBm** [geekSiddharth/DeepCoherence#1]
I've got this error 

> tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[468,75] = -1 is not in [0, 400001)
> 	 [[{{node embedding_2/embedding_lookup}} = GatherV2[Taxis=DT_INT32, Tindices=DT_INT32, Tparams=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](embedding_2/embeddings/read, embedding_2/Cast, embedding_2/embedding_lookup/axis)]]
> 
how to fix it please

**Comment by sedflix** [comment]
Hey, try using padding value of 0 in place of -1 in those three calls:
https://github.com/sedflix/DeepCoherence/blob/003be02a9c3e44e6a02d84183638b9a2662391ce/utills.py#L22

Let me know if it works.

**Comment by aminaBm** [comment]
> Hey, try using padding value of 0 in place of -1 in those three calls:
> https://github.com/sedflix/DeepCoherence/blob/003be02a9c3e44e6a02d84183638b9a2662391ce/utills.py#L22
> 
> Let me know if it works.

thank you it works well
